package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.56

import (
	"context"
	"errors"
	"fmt"
	"os"
	"strconv"

	"github.com/awanishnathpandey/leaf/db/generated"
	"github.com/awanishnathpandey/leaf/graph"
	"github.com/awanishnathpandey/leaf/graph/model"
	"github.com/awanishnathpandey/leaf/internal/utils"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.Register) (*model.User, error) {
	// Validate input
	if err := input.Validate(); err != nil {
		// Call the reusable validation error formatter
		return nil, utils.FormatValidationErrors(err)
	}

	// Hash the password
	hashedPassword, err := utils.HashPassword(input.Password)
	if err != nil {
		return nil, fmt.Errorf("failed to hash password: %w", err)
	}

	// Call the generated CreateUser function with the params
	user, err := r.DB.CreateUser(ctx, generated.CreateUserParams{
		FirstName: input.FirstName,
		LastName:  input.LastName,
		Email:     input.Email,
		Password:  hashedPassword,
	})
	if err != nil {
		return nil, err
	}

	// Return the newly created user
	return &model.User{
		ID:              user.ID,
		FirstName:       user.FirstName,
		LastName:        user.LastName,
		Email:           user.Email,
		JobTitle:        &user.JobTitle.String,
		LineOfBusiness:  &user.LineOfBusiness.String,
		LineManager:     &user.LineManager.String,
		EmailVerifiedAt: (*int64)(&user.EmailVerifiedAt.Int64),
		LastSeenAt:      user.LastSeenAt,
		CreatedAt:       user.CreatedAt,
		UpdatedAt:       user.UpdatedAt,
		DeletedAt:       (*int64)(&user.DeletedAt.Int64),
	}, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (*model.LoginResponse, error) {
	user, err := r.DB.GetUserByEmail(ctx, input.Email)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	if err := utils.CheckPassword(user.Password, input.Password); err != nil {
		return nil, fmt.Errorf("invalid credentials")
	}
	accessToken, err := utils.GenerateJWT(user.ID, user.Email, user.FirstName, user.LastName)
	if err != nil {
		return nil, fmt.Errorf("failed to generate access token")
	}
	jwtExpiryMinutes, err := strconv.Atoi(os.Getenv("JWT_EXPIRY_MINUTES"))
	if err != nil {
		return nil, fmt.Errorf("JWT_EXPIRY_MINUTES is invalid: %v", err)
	}

	refreshToken, err := utils.GenerateJWTRefresh(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate refresh token")
	}

	// Return the token and user in the response
	loginResponse := &model.LoginResponse{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    int64(jwtExpiryMinutes) * 60,
		User: &model.AuthUser{
			ID:             user.ID,
			FirstName:      user.FirstName,
			LastName:       user.LastName,
			Email:          user.Email,
			JobTitle:       &user.JobTitle.String,
			LineOfBusiness: &user.LineOfBusiness.String,
			LineManager:    &user.LineManager.String,
			LastSeenAt:     user.LastSeenAt,
			CreatedAt:      user.CreatedAt,
			UpdatedAt:      user.UpdatedAt,
		},
	}

	return loginResponse, nil
}

// ForgotPassword is the resolver for the forgotPassword field.
func (r *mutationResolver) ForgotPassword(ctx context.Context, input model.ForgotPassword) (bool, error) {
	panic(fmt.Errorf("not implemented: ForgotPassword - forgotPassword"))
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input model.ResetPassword) (bool, error) {
	panic(fmt.Errorf("not implemented: ResetPassword - resetPassword"))
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, input model.ChangePassword) (bool, error) {
	if input.NewPassword == "" || input.OldPassword == "" {
		return false, fmt.Errorf("password cannot be empty")
	}
	// Retrieve userID from context
	// userID := ctx.Value("userID").(int64) // Access the user ID from the context
	userEmail := ctx.Value("userEmail").(string)

	// Fetch user from DB based on the userID
	user, err := r.DB.GetUserByEmail(ctx, userEmail)
	if err != nil {
		return false, fmt.Errorf("user not found: %w", err)
	}
	// Validate the old password
	if err := utils.CheckPassword(user.Password, input.OldPassword); err != nil {
		return false, fmt.Errorf("incorrect old password")
	}

	// Hash the new password
	hashedPassword, err := utils.HashPassword(input.NewPassword)
	if err != nil {
		return false, fmt.Errorf("failed to hash password: %w", err)
	}
	// Update the user's password
	err = r.DB.UpdateUserPassword(ctx, generated.UpdateUserPasswordParams{
		Email:    user.Email,
		Password: hashedPassword,
	})
	if err != nil {
		return false, fmt.Errorf("failed to update password: %w", err)
	}

	return true, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, token string) (bool, error) {
	panic(fmt.Errorf("not implemented: VerifyEmail - verifyEmail"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input *model.RefreshToken) (*model.LoginResponse, error) {
	claims, err := utils.VerifyJWTRefresh(input.RefreshToken)
	if err != nil {
		return nil, errors.New("invalid or expired refresh token")
	}
	user, err := r.DB.GetUserByEmail(ctx, claims.Email)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}
	accessToken, err := utils.GenerateJWT(user.ID, user.Email, user.FirstName, user.LastName)
	if err != nil {
		return nil, fmt.Errorf("failed to generate access token")
	}
	jwtExpiryMinutes, err := strconv.Atoi(os.Getenv("JWT_EXPIRY_MINUTES"))
	if err != nil {
		return nil, fmt.Errorf("JWT_EXPIRY_MINUTES is invalid: %v", err)
	}

	refreshToken, err := utils.GenerateJWTRefresh(user.ID, user.Email)
	if err != nil {
		return nil, fmt.Errorf("failed to generate refresh token")
	}

	// Return the token and user in the response
	loginResponse := &model.LoginResponse{
		AccessToken:  accessToken,
		RefreshToken: refreshToken,
		ExpiresIn:    int64(jwtExpiryMinutes) * 60,
		User: &model.AuthUser{
			ID:             user.ID,
			FirstName:      user.FirstName,
			LastName:       user.LastName,
			Email:          user.Email,
			JobTitle:       &user.JobTitle.String,
			LineOfBusiness: &user.LineOfBusiness.String,
			LineManager:    &user.LineManager.String,
			LastSeenAt:     user.LastSeenAt,
			CreatedAt:      user.CreatedAt,
			UpdatedAt:      user.UpdatedAt,
		},
	}

	return loginResponse, nil

}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	// Retrieve userID from context
	// userID := ctx.Value("userID").(int64) // Access the user ID from the context
	userEmail := ctx.Value("userEmail").(string)

	// Fetch user from DB based on the userID
	user, err := r.DB.GetUserByEmail(ctx, userEmail)
	if err != nil {
		return nil, fmt.Errorf("user not found: %w", err)
	}

	// Map the generated.User to model.User
	modelUser := &model.User{
		ID:             user.ID, // Assuming both have the same field names
		FirstName:      user.FirstName,
		LastName:       user.LastName,
		Email:          user.Email,
		JobTitle:       &user.JobTitle.String,
		LineOfBusiness: &user.LineOfBusiness.String,
		LineManager:    &user.LineManager.String,
		LastSeenAt:     user.LastSeenAt,
		CreatedAt:      user.CreatedAt,
		UpdatedAt:      user.UpdatedAt,
	}

	return modelUser, nil
}

// Mutation returns graph.MutationResolver implementation.
func (r *Resolver) Mutation() graph.MutationResolver { return &mutationResolver{r} }

// Query returns graph.QueryResolver implementation.
func (r *Resolver) Query() graph.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
